config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users do
    resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :all_day

  has_many :user_event_mappings
  has_many :users, through: :user_event_mappings

  before_validation :filter_all_date, on: :create
  validate :end_time_with_start_time

  def end_time_with_start_time
    return true if end_time.blank? || start_time.blank?

    errors.add(:end_time, 'should be greater than the start time') if end_time < start_time
  end

  def filter_all_date
    return unless all_day

    self.start_time = start_time.beginning_of_day
    self.end_time = end_time.end_of_day
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_event_mappings
  has_many :events, through: :user_event_mappings
end

app/models/user_event_mapping.rb
class UserEventMapping < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum rsvp: { maybe: 0, yes: 1, no: 2 }

  before_save :handle_overlapping_events

  def handle_overlapping_events
    return true if rsvp != 'yes'

    events = user.events
                 .where('start_time >= ? AND end_time <= ? OR start_time >= ? AND end_time <= ?
                         OR start_time >= ? AND end_time <=? ',
                        event.start_time, event.start_time, event.end_time, event.end_time,
                        event.start_time, event.end_time)
    # rubocop:disable Rails/SkipsModelValidations
    user.user_event_mappings.where(event: events, rsvp: 'yes')&.update_all(rsvp: 'no')
    # rubocop:enable Rails/SkipsModelValidations
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_user
  def index
    @events = @user.events
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_index_table.html.haml
%td
  = event.title
%td
  = event.description
%td
  = event.start_time
%td
  = event.end_time
%td
  = event.user_event_mappings.first.rsvp

app/views/events/index.html.haml
%div
  = link_to 'Back', users_path
%div
  %h1 Events
  %table
    %th
      title
    %th
      description
    %th
      start_time
    %th
      end_time
    %th
      rsvp
    - @events.each do |event|
      %tr
        = render 'events/index_table', event: event

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_index_table.html.haml
%td
  = user.username
%td
  = user.phone
%td
  = link_to user.events.count, user_events_path(user)

app/views/users/index.html.haml
%div
  %h1 Users
  %table
    %th
      username
    %th
      phone
    %th
      events
    - @users.each do |user|
      %tr
        = render 'users/index_table', user: user